# Mengenal Konsep Variabel & Assignment

## Data Numeric

In [ ]:
tinggi_badan = 173

berapa isi dari variabel tinggi_badan sekarang?

In [ ]:
tinggi_badan

ganti nilai tinggi_badan dengan 170

In [ ]:
tinggi_badan = 170

berapa isi dari variabel tinggi_badan sekarang?

In [ ]:
tinggi_badan

In [ ]:
tinggi_badan/100

In [ ]:
tinggi_badan_in_m = tinggi_badan/100
tinggi_badan_in_m

## Data String

In [ ]:
nama_depan = 'Raffi'
nama_belakang = "Ahmad"

In [ ]:
nama_depan+nama_belakang

In [ ]:
nama_depan+" "+nama_belakang

## [CHALLENGE] Membuat variabel baru

In [ ]:
#buat variabel nama dan umur di sini

In [ ]:
"Halo, nama saya "+nama+". Umur saya adalah "+str(umur)+" tahun"

# Import Pandas Library

In [ ]:
import pandas as pd

# Membaca Dataset

In [ ]:
df_dataset = pd.read_csv('rakamin_class.csv')

In [ ]:
df_dataset

# Operasi Sederhana Data Frame

## a. info()

Melihat informasi tiap kolom di Data Frame

In [ ]:
df_dataset.info()

## b. columns

Melihat semua nama kolom

In [ ]:
df_dataset.columns

## c. shape

Melihat ukuran Data Frame (baris & kolom)

In [ ]:
df_dataset.shape

In [ ]:
df_dataset.shape[0]

In [ ]:
df_dataset.shape[1]

## d. describe()

Melihat statistik sederhana dari data (untuk kolom yang numerikal)

In [ ]:
df_dataset.describe()

## e. head()

Melihat N baris pertama  (default N=5)

In [ ]:
df_dataset.head()

In [ ]:
df_dataset.head(3)

## f. tail()

Melihat N baris terakhir (default N=5)

In [ ]:
df_dataset.tail()

In [ ]:
df_dataset.tail(3)

# Data Sorting

In [ ]:
df_dataset.head()

### Mengurutkan age dari termuda ke tertua (ASCENDING - Kecil ke besar)

In [ ]:
df_dataset.sort_values('age')

In [ ]:
df_dataset.sort_values('age', ascending=True)

### Mengurutkan age dari tertua ke termuda (DESCENDING - Besar ke Kecil)

In [ ]:
df_dataset.sort_values('age', ascending=False)

##

### Ambil data 10 orang pertama sesuai abjad

### [CHALLENGE] Ambil data 10 orang dengan score terendah

# Data Filtering

### Filter kolom name, email, phone, province

In [ ]:
df_dataset[ ['name','email','phone','province'] ].head()

## Ambil nama tiap orang beserta score nya

In [ ]:
df_dataset[['name','score']]

### Ambil data orang-orang dari Jakarta

In [ ]:
df_dataset[df_dataset['province']=='Jakarta']

### Ambil data orang-orang yang berusia lebih dari 30 tahun

In [ ]:
df_dataset[df_dataset['age'] > 30]

### Ambil data orang-orang dengan score <= 60

In [ ]:
df_dataset[df_dataset['score'] <= 60]

## Ada berapa orang yang punya score <= 60

### Ambil data orang-orang yang bukan dari kota Depok

In [ ]:
df_dataset[df_dataset['city'] != 'Depok']

## Ambil data orang-orang dari Jawa Timur dengan umur > 40

In [ ]:
df_dataset[ (df_dataset['province'] == 'Jawa Timur') & (df_dataset['age'] > 40) ]

## Ambil data orang-orang yang dari Surabaya, atau punya score > 90

In [ ]:
df_dataset[ (df_dataset['city'] == 'Surabaya') | (df_dataset['score'] > 90) ]

## Ambil data orang-orang yang bukan dari Malang

## Siapa orang paling tua yang berasal dari Jawa Tengah?

## [CHALLENGE] Ada berapa banyak orang di kelas 4 yang berasal dari Jawa Tengah?

## [CHALLENGE] Siapa nama pemilik no HP 628833542?

## Untuk semua orang di kelas 1, tunjukkan info nama, kota, dan provinsi nya

# Data Aggregation

## Melihat jumlah orang per provinsi

In [ ]:
df_dataset.groupby('province')['registration_id'].count()

Tambahkan .reset_index() untuk membuat dataframe yang kolomnya rata

## Melihat rata-rata score tiap kelas

In [ ]:
df_dataset.groupby('class')['score'].mean().reset_index()

diurutkan dari rata-rata score tertinggi

In [ ]:
df_dataset.groupby('class')['score'].mean().reset_index().sort_values('score',ascending=False)

## Melihat score terbesar per provinsi per kelas

In [ ]:
df_dataset.groupby(['province','class'])['score'].max().reset_index()

Untuk masing-masing kota dan provinsi, berapa usia termudanya?

In [ ]:
df_dataset.groupby(['province','city'])['age'].min().reset_index()

## Untuk orang-orang dari Jakarta, berapa rata-rata score per kota?

## [CHALLENGE] Berapa banyak orang yang aktif, dan tidak aktif?